//user
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_ERROR = "EMAIL_VERIFICATION_ERROR";
export const MOBILE_VERIFICATION = "MOBILE_VERIFICATION";
export const MOBILE_VERIFICATION_SUCCESS = "MOBILE_VERIFICATION_SUCCESS";
export const MOBILE_VERIFICATION_ERROR = "MOBILE_VERIFICATION_ERROR";
export const OTP_VERIFICATION = "OTP_VERIFICATION";
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS";
export const OTP_VERIFICATION_ERROR = "OTP_VERIFICATION_ERROR";
export const SET_TOKEN = "SET_TOKEN";
export const SET_PROFILE = "SET_PROFILE";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";
export const RESET_USER_FLAGS = "RESET_USER_FLAGS";
export const SET_SELECTED_DRAWER_ITEM = "SET_SELECTED_DRAWER_ITEM";

//investor
export const ADD_SINGLE_INVESTOR = "ADD_SINGLE_INVESTOR";
export const ADD_SINGLE_INVESTOR_SUCCESS = "ADD_SINGLE_INVESTOR_SUCCESS";
export const ADD_SINGLE_INVESTOR_ERROR = "ADD_SINGLE_INVESTOR_ERROR";
export const GET_EXCHANGE_INVESTOR_DATA = "GET_EXCHANGE_INVESTOR_DATA";
export const GET_EXCHANGE_INVESTOR_DATA_SUCCESS =
	"GET_EXCHANGE_INVESTOR_DATA_SUCCESS";
export const GET_EXCHANGE_INVESTOR_DATA_ERROR =
	"GET_EXCHANGE_INVESTOR_DATA_ERROR";
export const VERIFY_INVESTOR_EMAIL = "VERIFY_INVESTOR_EMAIL";
export const VERIFY_INVESTOR_EMAIL_SUCCESS = "VERIFY_INVESTOR_EMAIL_SUCCESS";
export const VERIFY_INVESTOR_EMAIL_ERROR = "VERIFY_INVESTOR_EMAIL_ERROR";
export const VERIFY_INVESTOR_MOBILE = "VERIFY_INVESTOR_MOBILE";
export const VERIFY_INVESTOR_MOBILE_SUCCESS = "VERIFY_INVESTOR_MOBILE_SUCCESS";
export const VERIFY_INVESTOR_MOBILE_ERROR = "VERIFY_INVESTOR_MOBILE_ERROR";
export const RESET_INVESTOR_FLAGS = "RESET_INVESTOR_FLAGS";
